export const FETCH_CURRENT_WEATHER_REQUEST = 'FETCH_CURRENT_WEATHER_REQUEST';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAILURE = 'FETCH_CURRENT_WEATHER_FAILURE';

export const FETCH_ASTRONOMY_WEATHER_REQUEST = 'FETCH_ASTRONOMY_WEATHER_REQUEST';
export const FETCH_ASTRONOMY_WEATHER_SUCCESS = 'FETCH_ASTRONOMY_WEATHER_SUCCESS';
export const FETCH_ASTRONOMY_WEATHER_FAILURE = 'FETCH_ASTRONOMY_WEATHER_FAILURE';

export const FETCH_FORECAST_WEATHER_REQUEST = 'FETCH_FORECAST_WEATHER_REQUEST';
export const FETCH_FORECAST_WEATHER_SUCCESS = 'FETCH_FORECAST_WEATHER_SUCCESS';
export const FETCH_FORECAST_WEATHER_FAILURE = 'FETCH_FORECAST_WEATHER_FAILURE';