export const GET_CURRENT_WEATHER_PENDING = 'GET_CURRENT_WEATHER_PENDING';
export const GET_CURRENT_WEATHER_FAILED = 'GET_CURRENT_WEATHER_FAILED';
export const GET_CURRENT_WEATHER_SUCCEEDED = 'GET_CURRENT_WEATHER_SUCCEEDED';
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';

export const GET_ASTRONOMY_WEATHER_PENDING = 'GET_ASTRONOMY_WEATHER_PENDING';
export const GET_ASTRONOMY_WEATHER_FAILED = 'GET_ASTRONOMY_WEATHER_FAILED';
export const GET_ASTRONOMY_WEATHER_SUCCEEDED = 'GET_ASTRONOMY_WEATHER_SUCCEEDED';
export const GET_ASTRONOMY_WEATHER = 'GET_ASTRONOMY_WEATHER';